source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.9"

gem "rails",           "7.0.10"
gem "sassc-rails",     "2.1.2"
gem "sprockets-rails", "3.4.2"
gem "importmap-rails", "1.1.5"
gem "turbo-rails",     "1.4.0"
gem "stimulus-rails",  "1.2.1"
gem "jbuilder",        "2.11.5"
gem "puma",            "5.6.8"
gem "bootsnap",        "1.16.0", require: false
gem "pg"
gem "concurrent-ruby", "1.3.4"

group :development, :test do
  gem "reline",              "0.5.10"
  gem "debug",               "1.7.1", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "rubocop",             require: false
  gem "rubocop-rails",       require: false
  gem "rubocop-rspec",       require: false
end

group :development do
  gem "web-console",         "4.2.0"
  gem "solargraph",          "0.56.2"
  gem "irb",                 "1.10.0"
  gem "repl_type_completor", "0.1.10"
end

group :test do
  gem "capybara",                 "3.38.0"
  gem "selenium-webdriver",       "4.8.3"
  gem "webdrivers",               "5.2.0"
  gem "rails-controller-testing", "1.0.5"
end

# gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
